import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { MapContainer, TileLayer, Marker, Polygon, useMapEvents } from 'react-leaflet';
import '../../lib/leafletIcons';
import type { LatLngExpression } from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { apiDelete, apiPatch, apiPost, fieldError, useApiQuery } from '../../api/client';
import type { ListResponse } from '../../api/types';
import type { SiteDto } from '../../api/generated/SiteDto';
import type { SiteRequest } from '../../api/generated/SiteRequest';
import type { PatchSiteRequest } from '../../api/generated/PatchSiteRequest';
import { Banner, Button, Card, CardBody, CardHeader, Checkbox, Dialog, FormField, Input, StatusBadge, useToast } from '../../ui';
import { useProjectContext } from '../projects/projectContext';
import { QueryState } from '../application/shared';
import { usePermissions } from '../application/permissions';

const centre: LatLngExpression = [-25.066, -130.100];
function ClickPoints({ onAdd, enabled }: { onAdd: (point: [number, number]) => void; enabled: boolean }) { useMapEvents({ click(e) { if (enabled) onAdd([e.latlng.lat, e.latlng.lng]); } }); return null; }
function shape(site: SiteDto) {
  const coordinates = site.geometry.coordinates;
  if (site.geometry.type === 'Point' && Array.isArray(coordinates)) return <Marker key={site.id} position={[Number(coordinates[1]), Number(coordinates[0])]} />;
  if (site.geometry.type === 'Polygon' && Array.isArray(coordinates) && Array.isArray(coordinates[0])) return <Polygon key={site.id} positions={(coordinates[0] as number[][]).map(p => [p[1], p[0]] as LatLngExpression)} pathOptions={{ color: site.generalized ? '#64748b' : '#0f766e', dashArray: site.generalized ? '6 6' : undefined }} />;
  return null;
}

export function SitesTab() {
  const { project } = useProjectContext(); const rights = usePermissions(); const query = useQueryClient(); const toast = useToast();
  const key = ['projects', project.id, 'sites']; const sites = useApiQuery<ListResponse<SiteDto>>(key, `/projects/${project.id}/sites`);
  const [name, setName] = useState(''); const [sensitive, setSensitive] = useState(false); const [points, setPoints] = useState<[number, number][]>([]); const [lat, setLat] = useState(''); const [lng, setLng] = useState(''); const [mode, setMode] = useState<'point' | 'polygon'>('point'); const [editing, setEditing] = useState<SiteDto | null>(null); const [deleting, setDeleting] = useState<SiteDto | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  const canEdit = rights.canEdit;
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); setError(null); try { await action(); toast.success(message); await query.invalidateQueries({ queryKey: key }); } catch (e) { setError(e); toast.error('Could not update site', e instanceof Error ? e.message : undefined); } finally { setBusy(false); } }
  function addPoint() { const a = Number(lat), b = Number(lng); if (!Number.isFinite(a) || !Number.isFinite(b) || a < -90 || a > 90 || b < -180 || b > 180) { setError(new Error('Enter a valid latitude and longitude.')); return; } setPoints(p => [...p, [a, b]]); setLat(''); setLng(''); setError(null); }
  async function save() { const coordinates = mode === 'point' ? [points[0][1], points[0][0]] : [[...points.map(p => [p[1], p[0]]), [points[0][1], points[0][0]]]]; const geometry = { type: mode === 'point' ? 'Point' : 'Polygon', coordinates }; await run(async () => { if (editing) await apiPatch(`/sites/${editing.id}`, { name, geometry, sensitive } satisfies PatchSiteRequest); else await apiPost(`/projects/${project.id}/sites`, { name, geometry, sensitive } satisfies SiteRequest); setName(''); setSensitive(false); setPoints([]); setEditing(null); }, editing ? 'Site updated' : 'Site added'); }
  function edit(s: SiteDto) { setEditing(s); setName(s.name); setSensitive(s.sensitive); const coords = s.geometry.coordinates; if (s.geometry.type === 'Point' && Array.isArray(coords)) { setMode('point'); setPoints([[Number(coords[1]), Number(coords[0])]]); } else if (Array.isArray(coords) && Array.isArray(coords[0])) { setMode('polygon'); setPoints((coords[0] as number[][]).slice(0, -1).map(p => [p[1], p[0]])); } }
  return <div className="space-y-5"><Card><CardHeader title="Research sites" actions={<a href={`/api/v1/projects/${project.id}/sites.geojson`} className="text-sm font-medium text-teal-700 underline" download>Download GeoJSON</a>} /><CardBody className="space-y-3"><div className="h-80 overflow-hidden rounded-md" role="application" aria-label="Site map"><MapContainer center={centre} zoom={8} scrollWheelZoom={false} className="h-full w-full"><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' /><ClickPoints onAdd={p => setPoints(old => [...old, p])} enabled={canEdit} />{sites.data?.items.map(shape)}{points.length >= 3 && mode === 'polygon' && <Polygon positions={points} pathOptions={{ color: '#0f766e' }} />}{points.length === 1 && mode === 'point' && <Marker position={points[0]} />}</MapContainer></div><p className="text-sm text-slate-600">Select points on the map or enter coordinates below. Dashed boxes show generalized locations; exact locations are hidden outside the team and Pitcairn staff.</p><QueryState loading={sites.isPending} error={sites.error} empty={sites.data?.items.length === 0}><ul className="space-y-2">{sites.data?.items.map(s => <li key={s.id} className="flex flex-wrap items-center justify-between gap-2 rounded border border-slate-200 p-3"><div><strong>{s.name}</strong> {s.sensitive && <StatusBadge status="active" label="Sensitive" />}{s.generalized && <span className="text-sm">Generalized area</span>}</div>{canEdit && <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => edit(s)}>Edit</Button><Button size="sm" variant="secondary" onClick={() => setDeleting(s)}>Delete</Button></div>}</li>)}</ul></QueryState></CardBody></Card>
    {canEdit && <Card><CardHeader title={editing ? `Edit ${editing.name}` : 'Add a site'} /><CardBody className="space-y-3">{Boolean(error) && <Banner tone="error">{error instanceof Error ? error.message : 'Could not save site.'}</Banner>}<FormField label="Site name" error={fieldError(error, 'name')}><Input value={name} onChange={e => setName(e.target.value)} /></FormField><div className="flex gap-3"><label><input type="radio" name="shape" checked={mode === 'point'} onChange={() => { setMode('point'); setPoints([]); }} /> Point</label><label><input type="radio" name="shape" checked={mode === 'polygon'} onChange={() => { setMode('polygon'); setPoints([]); }} /> Polygon</label></div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><FormField label="Latitude"><Input type="number" step="any" min="-90" max="90" value={lat} onChange={e => setLat(e.target.value)} /></FormField><FormField label="Longitude"><Input type="number" step="any" min="-180" max="180" value={lng} onChange={e => setLng(e.target.value)} /></FormField><Button variant="secondary" disabled={!lat || !lng} onClick={addPoint}>Add point</Button></div><ol className="list-decimal pl-5 text-sm">{points.map((p, i) => <li key={i}>{p[0].toFixed(5)}, {p[1].toFixed(5)} <button className="text-red-700 underline" onClick={() => setPoints(old => old.filter((_, j) => i !== j))}>Remove</button></li>)}</ol><Checkbox checked={sensitive} onChange={e => setSensitive(e.target.checked)} label="Sensitive location" /><p className="text-sm text-slate-600">Exact location hidden outside the team and Pitcairn staff.</p><div className="flex gap-2"><Button loading={busy} disabled={!name.trim() || points.length < (mode === 'point' ? 1 : 3)} onClick={save}>{editing ? 'Save site' : 'Add site'}</Button>{editing && <Button variant="secondary" onClick={() => { setEditing(null); setPoints([]); setName(''); }}>Cancel edit</Button>}</div></CardBody></Card>}
    <Dialog open={Boolean(deleting)} onClose={() => setDeleting(null)} title="Delete site" footer={<><Button variant="secondary" onClick={() => setDeleting(null)}>Keep site</Button><Button loading={busy} onClick={async () => { if (!deleting) return; await run(() => apiDelete(`/sites/${deleting.id}`), 'Site deleted'); setDeleting(null); }}>Delete site</Button></>}><p>This removes {deleting?.name} from the project and future application revisions.</p></Dialog>
  </div>;
}
