import { decisionKindLabel } from '../../lib/decisionKind';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router';
import { apiPost, useApiQuery } from '../../api/client';
import type { ListResponse } from '../../api/types';
import type { DecisionDto } from '../../api/generated/DecisionDto';
import type { ThreadDto } from '../../api/generated/ThreadDto';
import { Button, Card, CardBody, CardHeader, KeyValue, StatusBadge, useToast } from '../../ui';
import { useProjectContext } from '../projects/projectContext';
import { DateText, QueryState, SectionLink } from './shared';
import { usePermissions } from './permissions';

export function OverviewTab() {
  const { project, workspace } = useProjectContext(); const rights = usePermissions(); const toast = useToast(); const query = useQueryClient(); const navigate = useNavigate(); const [screening, setScreening] = useState(false);
  const decisions = useApiQuery<ListResponse<DecisionDto>>(['projects', project.id, 'decisions'], `/projects/${project.id}/decisions`);
  const threads = useApiQuery<ListResponse<ThreadDto>>(['projects', project.id, 'threads'], `/projects/${project.id}/threads`, { enabled: Boolean(workspace.primary_message?.thread_id) });
  const message = workspace.primary_message;
  const thread = threads.data?.items.find(t => t.id === message?.thread_id);
  const anchor = thread ? `${thread.anchor_type}:${thread.anchor_key}` : 'project:';
  const base = `/app/projects/${project.id}`;
  const reply = message?.review_id ? `${base}/review` : `${base}/messages?thread=${message?.thread_id ?? ''}`;
  const upload = thread?.anchor_type === 'document' ? `${base}/application?anchor=documents.${thread.anchor_key}` : `${base}/application?anchor=answers.${thread?.anchor_key ?? ''}`;
  const current = decisions.data?.items.find(d => d.status === 'issued' && !d.superseded_by_id);
  async function screen() { setScreening(true); try { await apiPost(`/projects/${project.id}/screen`); toast.success('Application opened for screening'); await query.invalidateQueries({ queryKey: ['projects', project.id] }); } catch (e) { toast.error('Could not open for screening', e instanceof Error ? e.message : undefined); } finally { setScreening(false); } }
  return <div className="grid gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2">{message && <Card><CardHeader title="What needs attention" /><CardBody className="space-y-3"><p className="text-lg font-semibold text-navy-900">{message.text}</p><p className="text-sm text-slate-600">About {thread ? `${thread.anchor_type}: ${thread.anchor_key || 'project'}` : 'this project'} · <DateText value={message.created_at} time /></p><div className="flex flex-wrap gap-2"><Button onClick={() => { navigate(reply); }}>Reply</Button>{thread?.anchor_type === 'document' && <Link className="rounded-md border px-3 py-2 text-sm" to={upload}>Upload document</Link>}{thread?.anchor_type === 'field' && <Link className="rounded-md border px-3 py-2 text-sm" to={upload}>Open field</Link>}</div></CardBody></Card>}
    <Card><CardHeader title="Project at a glance" /><CardBody><KeyValue items={[{ key: 'Status', value: <StatusBadge status={project.status} label={project.status === 'approved' ? 'Permit decision issued' : undefined} /> }, { key: 'Reference', value: project.reference ?? 'Assigned when submitted' }, { key: 'Start', value: <DateText value={project.start_date} /> }, { key: 'End', value: <DateText value={project.end_date} /> }, { key: 'Created', value: <DateText value={project.created_at} time /> }, { key: 'Organisation', value: project.organisation || '—' }]} /><p className="mt-4 text-sm">{project.summary}</p></CardBody></Card>
    <Card><CardHeader title="Decision" /><CardBody><QueryState loading={decisions.isPending} error={decisions.error} empty={!current}>{current && <div className="space-y-2"><p className="font-semibold">{current.kind === 'refusal' ? 'Application refused' : `Current decision: ${decisionKindLabel(current.kind)}`}</p><p className="text-sm">{current.basis}</p><p className="text-sm">Valid <DateText value={current.valid_from} /> to <DateText value={current.valid_to} /></p><p className="text-sm">Permitted activities: {current.permitted_activities.join('; ') || 'None'}</p><p className="text-sm">Conditions: {current.conditions.join('; ') || 'None'}</p><SectionLink to={`${base}/decisions`}>Read full decision</SectionLink></div>}</QueryState></CardBody></Card>
  </div><div className="space-y-5"><Card><CardHeader title="Team" /><CardBody><ul className="space-y-2 text-sm">{workspace.application.team.map(m => <li key={m.user_id}>{m.name} · {m.role}</li>)}</ul><SectionLink to={`${base}/team`}>View team</SectionLink></CardBody></Card><Card><CardHeader title="Next steps" /><CardBody className="space-y-2 text-sm">{rights.teamEditor ? <p>{project.status === 'draft' ? 'Complete the form and required documents, then submit.' : project.status === 'changes_requested' ? 'Reply to the request, update the application, then resubmit.' : current ? 'Read the decision and its conditions before fieldwork.' : 'Wait for screening and respond to any requests.'}</p> : <p>{project.status === 'submitted' ? 'Open this application for screening.' : project.status === 'in_review' ? 'Review expert advice and prepare a decision.' : current ? 'Monitor the permit conditions and delivery dates.' : 'Review the project record.'}</p>}{rights.coordinator && <div className="flex flex-col items-start gap-2">{project.status === 'submitted' && <Button size="sm" loading={screening} onClick={screen}>Open for screening</Button>}{['submitted', 'in_review'].includes(project.status) && <SectionLink to={`${base}/messages?anchor=${anchor}`}>Request information</SectionLink>}{['submitted', 'in_review', 'changes_requested'].includes(project.status) && <SectionLink to={`${base}/review`}>Assign expert</SectionLink>}{project.status === 'in_review' && <SectionLink to={`${base}/decisions`}>Draft decision</SectionLink>}</div>}</CardBody></Card></div></div>;
}
