import { useState } from 'react';
import { Link } from 'react-router';
import { ApplicationTab } from '../application/ApplicationTab';
import { useQueryClient } from '@tanstack/react-query';
import { apiPost, fieldError, useApiQuery } from '../../api/client';
import type { ListResponse, UserDto } from '../../api/types';
import type { CreateReviewRequest } from '../../api/generated/CreateReviewRequest';
import type { ReviewAssignmentDto } from '../../api/generated/ReviewAssignmentDto';
import type { DeclineRequest } from '../../api/generated/DeclineRequest';
import type { SubmitOpinionRequest } from '../../api/generated/SubmitOpinionRequest';
import { Banner, Button, Card, CardBody, CardHeader, FormField, Input, Select, StatusBadge, Textarea, useToast } from '../../ui';
import { useProjectContext } from '../projects/ProjectLayout';
import { DateText, QueryState, usePermissions } from '../application/shared';

export function ReviewTab() {
  const { project, me } = useProjectContext(); const rights = usePermissions(); const query = useQueryClient(); const toast = useToast();
  const key = ['projects', project.id, 'reviews'];
  const reviews = useApiQuery<ListResponse<ReviewAssignmentDto>>(key, `/projects/${project.id}/reviews`, { enabled: rights.coordinator || rights.decisionMaker || rights.expert });
  const experts = useApiQuery<ListResponse<UserDto>>(['review-experts'], '/review-experts', { enabled: rights.coordinator });
  const [expertId, setExpertId] = useState(''); const [due, setDue] = useState(''); const [opinion, setOpinion] = useState(''); const [recommendation, setRecommendation] = useState('approve_with_conditions'); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); setError(null); try { await action(); toast.success(message); await query.invalidateQueries({ queryKey: key }); } catch (e) { setError(e); toast.error('Could not update review', e instanceof Error ? e.message : undefined); } finally { setBusy(false); } }
  const mine = reviews.data?.items.find(r => r.expert_id === me?.user.id && ['invited', 'accepted'].includes(r.status));
  return <div className="space-y-5">{Boolean(error) && <Banner tone="error">{error instanceof Error ? error.message : 'Could not update review.'}</Banner>}{rights.coordinator && ['submitted', 'in_review', 'changes_requested'].includes(project.status) && <Card><CardHeader title="Assign an expert" /><CardBody className="space-y-3"><QueryState loading={experts.isPending} error={experts.error} empty={experts.data?.items.length === 0}><FormField label="Expert" error={fieldError(error, 'expert_id')}><Select value={expertId} onChange={e => setExpertId(e.target.value)}><option value="">Choose an expert</option>{experts.data?.items.map(u => <option key={u.id} value={u.id}>{u.name} · {u.organisation}</option>)}</Select></FormField><FormField label="Due date" error={fieldError(error, 'due_date')}><Input type="date" value={due} onChange={e => setDue(e.target.value)} /></FormField><Button loading={busy} disabled={!expertId} onClick={() => void run(() => apiPost(`/projects/${project.id}/reviews`, { expert_id: expertId, due_date: due || null } satisfies CreateReviewRequest), 'Expert invited')}>Assign expert</Button></QueryState></CardBody></Card>}
    {(rights.coordinator || rights.decisionMaker || rights.expert) && <Card><CardHeader title="Expert assignments" /><CardBody><QueryState loading={reviews.isPending} error={reviews.error} empty={reviews.data?.items.length === 0}><ul className="space-y-3">{reviews.data?.items.map(r => <li key={r.id} className="rounded-md border border-slate-200 p-3"><strong>{r.expert_name}</strong> · revision {String(r.revision_number)} <StatusBadge status={r.status} /><p className="text-sm">Due <DateText value={r.due_date} />{r.decline_reason && ` · Declined: ${r.decline_reason}`}</p>{r.opinion && <p className="mt-2 whitespace-pre-wrap text-sm"><strong>Opinion:</strong> {r.opinion}<br /><strong>Recommendation:</strong> {r.recommendation?.replaceAll('_', ' ')}</p>}</li>)}</ul></QueryState></CardBody></Card>}
    {rights.expert && mine && <Card><CardHeader title="Your review" /><CardBody className="space-y-3"><p className="text-sm">Read the application and documents below before responding.</p>{mine.status === 'invited' && <><Button loading={busy} onClick={() => void run(() => apiPost(`/reviews/${mine.id}/accept`), 'Review accepted')}>Accept assignment</Button><FormField label="Reason for declining" error={fieldError(error, 'reason')}><Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Describe the conflict of interest or other reason" /></FormField><Button variant="secondary" loading={busy} disabled={!reason.trim()} onClick={() => void run(() => apiPost(`/reviews/${mine.id}/decline`, { reason } satisfies DeclineRequest), 'Assignment declined')}>Decline assignment</Button></>}{mine.status === 'accepted' && <><FormField label="Opinion" error={fieldError(error, 'opinion')}><Textarea value={opinion} onChange={e => setOpinion(e.target.value)} /></FormField><FormField label="Recommendation" error={fieldError(error, 'recommendation')}><Select value={recommendation} onChange={e => setRecommendation(e.target.value)}><option value="approve">Approve</option><option value="approve_with_conditions">Approve with conditions</option><option value="reject">Reject</option><option value="need_more_info">Need more information</option></Select></FormField><Button loading={busy} disabled={!opinion.trim()} onClick={() => void run(() => apiPost(`/reviews/${mine.id}/submit`, { opinion, recommendation } satisfies SubmitOpinionRequest), 'Opinion submitted')}>Submit opinion</Button></>}</CardBody></Card>}{rights.expert && <ApplicationTab />}</div>;
}

export function MyReviewsPage() {
  const reviews = useApiQuery<ListResponse<ReviewAssignmentDto>>(['my-reviews'], '/reviews');
  return <main className="space-y-4"><h1 className="text-2xl font-semibold">My expert reviews</h1><QueryState loading={reviews.isPending} error={reviews.error} empty={reviews.data?.items.length === 0}><ul className="space-y-3">{reviews.data?.items.map(r => <li key={r.id} className="rounded-lg border border-slate-200 bg-white p-4"><Link className="font-semibold text-teal-700 underline" to={`/app/projects/${r.project_id}/review`}>{r.project_reference ?? r.project_title}</Link><p className="text-sm">Revision {String(r.revision_number)} · due <DateText value={r.due_date} /> · <StatusBadge status={r.status} /></p></li>)}</ul></QueryState></main>;
}
