import { decisionKindLabel } from '../../lib/decisionKind';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { apiPost, fieldError, useApiQuery } from '../../api/client';
import type { ListResponse } from '../../api/types';
import type { DecisionDto } from '../../api/generated/DecisionDto';
import type { ChangeRequestDto } from '../../api/generated/ChangeRequestDto';
import type { ChangeRequestImpactDto } from '../../api/generated/ChangeRequestImpactDto';
import type { CreateChangeRequestRequest } from '../../api/generated/CreateChangeRequestRequest';
import type { ResolveChangeRequestRequest } from '../../api/generated/ResolveChangeRequestRequest';
import type { RejectChangeRequestRequest } from '../../api/generated/RejectChangeRequestRequest';
import { Banner, Button, Card, CardBody, CardHeader, FormField, Input, Select, StatusBadge, Textarea, useToast } from '../../ui';
import { useProjectContext } from '../projects/projectContext';
import { DateText, QueryState } from '../application/shared';
import { usePermissions } from '../application/permissions';

function Impact({ id }: { id: string }) {
  const impact = useApiQuery<ChangeRequestImpactDto>(['change-requests', id, 'impact'], `/change-requests/${id}/impact`);
  return <div className="mt-3 rounded-md bg-slate-50 p-3"><h3 className="font-semibold">Impact and next actions</h3><QueryState loading={impact.isPending} error={impact.error}><ul className="mt-2 space-y-2 text-sm">{impact.data?.bookings.map(b => <li key={b.booking_id}>Booking: {b.resource_name} · {b.kind === 'conflict' ? 'Conflict' : 'Will be re-requested'} <StatusBadge status="open" label="Needs action" /></li>)}{impact.data?.deliverables.map(d => <li key={d.id}>Deliverable: {d.title} · due <DateText value={d.due_date} /> <StatusBadge status="open" label="Needs action" /></li>)}{impact.data?.decisions.map(d => <li key={d.id}>Decision: {decisionKindLabel(d.kind)} · validity ends <DateText value={d.valid_to} /> <StatusBadge status="open" label="Needs action" /></li>)}{impact.data?.notes.map((note, i) => <li key={i}>{note}</li>)}{impact.data && !impact.data.bookings.length && !impact.data.deliverables.length && !impact.data.decisions.length && !impact.data.notes.length && <li>No linked items need action.</li>}</ul></QueryState></div>;
}

export function ChangesTab() {
  const { project, workspace } = useProjectContext(); const rights = usePermissions(); const query = useQueryClient(); const toast = useToast();
  const key = ['projects', project.id, 'change-requests']; const changes = useApiQuery<ListResponse<ChangeRequestDto>>(key, `/projects/${project.id}/change-requests`); const decisions = useApiQuery<ListResponse<DecisionDto>>(['projects', project.id, 'decisions'], `/projects/${project.id}/decisions`, { enabled: rights.coordinator || rights.decisionMaker });
  const [kind, setKind] = useState('reschedule_trip'); const [description, setDescription] = useState(''); const [trip, setTrip] = useState(''); const [arrive, setArrive] = useState(''); const [depart, setDepart] = useState(''); const [validTo, setValidTo] = useState(''); const [note, setNote] = useState<Record<string, string>>({}); const [decisionId, setDecisionId] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setError(null); try { await action(); toast.success(success); await query.invalidateQueries({ queryKey: key }); } catch (e) { setError(e); toast.error('Could not update request', e instanceof Error ? e.message : undefined); } finally { setBusy(false); } }
  function payload(): Record<string, unknown> { if (kind === 'reschedule_trip') return { trip_id: trip, new_arrive_date: arrive, new_depart_date: depart }; if (kind === 'extend_permit') return { new_valid_to: validTo }; return {}; }
  return <div className="space-y-5">{Boolean(error) && <Banner tone="error">{error instanceof Error ? error.message : 'Could not save request.'}</Banner>}{rights.teamEditor && <Card><CardHeader title="Request a change" /><CardBody className="space-y-3"><FormField label="Type" error={fieldError(error, 'kind')}><Select value={kind} onChange={e => setKind(e.target.value)}><option value="reschedule_trip">Reschedule trip</option><option value="extend_permit">Extend permit</option><option value="expand_scope">Expand scope</option><option value="other">Other</option></Select></FormField>{kind === 'reschedule_trip' && <><FormField label="Trip" error={fieldError(error, 'payload.trip_id')}><Select value={trip} onChange={e => setTrip(e.target.value)}><option value="">Choose trip</option>{workspace.trips.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</Select></FormField><div className="grid gap-3 sm:grid-cols-2"><FormField label="New arrival" error={fieldError(error, 'payload.new_arrive_date')}><Input type="date" value={arrive} onChange={e => setArrive(e.target.value)} /></FormField><FormField label="New departure" error={fieldError(error, 'payload.new_depart_date')}><Input type="date" value={depart} onChange={e => setDepart(e.target.value)} /></FormField></div></>}{kind === 'extend_permit' && <FormField label="Requested end date" error={fieldError(error, 'payload.new_valid_to')}><Input type="date" value={validTo} onChange={e => setValidTo(e.target.value)} /></FormField>}<FormField label="Describe the change" error={fieldError(error, 'description')}><Textarea value={description} onChange={e => setDescription(e.target.value)} /></FormField><Button loading={busy} disabled={!description.trim()} onClick={() => void run(() => apiPost(`/projects/${project.id}/change-requests`, { kind, description, payload: payload() } satisfies CreateChangeRequestRequest), 'Change requested')}>Send change request</Button></CardBody></Card>}
    <Card><CardHeader title="Change requests" /><CardBody><QueryState loading={changes.isPending} error={changes.error} empty={changes.data?.items.length === 0}><ul className="space-y-4">{changes.data?.items.map(c => <li key={c.id} className="rounded-md border border-slate-200 p-3"><div className="flex flex-wrap gap-2"><strong>{c.kind.replaceAll('_', ' ')}</strong><StatusBadge status={c.status} /></div><p className="text-sm">{c.description}</p><p className="text-xs text-slate-500">{c.requested_by_name} · <DateText value={c.created_at} time /></p>{c.resolution_note && <p className="mt-2 text-sm">Resolution: {c.resolution_note}</p>}{c.status === 'open' && <Impact id={c.id} />}{(rights.coordinator || rights.decisionMaker) && c.status === 'open' && <div className="mt-3 space-y-2"><FormField label={`Resolution note for ${c.kind}`}><Input value={note[c.id] ?? ''} onChange={e => setNote(v => ({ ...v, [c.id]: e.target.value }))} /></FormField>{['extend_permit', 'expand_scope'].includes(c.kind) && <FormField label="Issued decision implementing this change" error={fieldError(error, 'resulting_decision_id')}><Select value={decisionId[c.id] ?? ''} onChange={e => setDecisionId(v => ({ ...v, [c.id]: e.target.value }))}><option value="">Choose issued decision</option>{decisions.data?.items.filter(d => d.status === 'issued').map(d => <option key={d.id} value={d.id}>{decisionKindLabel(d.kind)} · {String(d.revision_number)}</option>)}</Select></FormField>}<div className="flex gap-2"><Button loading={busy} disabled={['extend_permit', 'expand_scope'].includes(c.kind) && !decisionId[c.id]} onClick={() => void run(() => apiPost(`/change-requests/${c.id}/approve`, { resulting_decision_id: decisionId[c.id] || null, note: note[c.id] || null } satisfies ResolveChangeRequestRequest), 'Change approved')}>Approve</Button><Button variant="secondary" loading={busy} onClick={() => void run(() => apiPost(`/change-requests/${c.id}/reject`, { note: note[c.id] || null } satisfies RejectChangeRequestRequest), 'Change rejected')}>Reject</Button></div></div>}</li>)}</ul></QueryState></CardBody></Card></div>;
}
