import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router';
import { useQueryClient } from '@tanstack/react-query';
import { apiPost, fieldError, useApiQuery } from '../../api/client';
import type { ListResponse } from '../../api/types';
import type { CreateThreadRequest } from '../../api/generated/CreateThreadRequest';
import type { PostMessageRequest } from '../../api/generated/PostMessageRequest';
import type { ThreadDto } from '../../api/generated/ThreadDto';
import { Banner, Button, Card, CardBody, CardHeader, Checkbox, FormField, Input, Select, StatusBadge, Textarea, useToast } from '../../ui';
import { useProjectContext } from '../projects/projectContext';
import { DateText, QueryState } from '../application/shared';
import { usePermissions } from '../application/permissions';

export function MessagesTab() {
  const { project } = useProjectContext(); const rights = usePermissions(); const [params] = useSearchParams(); const query = useQueryClient(); const toast = useToast();
  const key = ['projects', project.id, 'threads']; const threads = useApiQuery<ListResponse<ThreadDto>>(key, `/projects/${project.id}/threads`);
  const [body, setBody] = useState(''); const [visibility, setVisibility] = useState(rights.expert ? 'internal' : 'shared'); const [request, setRequest] = useState(false); const [requestTitle, setRequestTitle] = useState('');
  const [replies, setReplies] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  const selectedAnchor = params.get('anchor')?.split(':') ?? ['project', ''];
  useEffect(() => { const id = params.get('thread'); if (id && threads.data) document.getElementById(`thread-${id}`)?.scrollIntoView({ block: 'center' }); }, [params, threads.data]);
  const canWrite = rights.teamEditor || rights.canComment;
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setError(null); try { await action(); toast.success(success); await query.invalidateQueries({ queryKey: key }); } catch (e) { setError(e); toast.error('Could not update messages', e instanceof Error ? e.message : undefined); } finally { setBusy(false); } }
  async function create() { await run(async () => { await apiPost(`/projects/${project.id}/threads`, { anchor_type: selectedAnchor[0], anchor_key: selectedAnchor[1] || null, visibility, body, action_item: request ? { addressed_to: 'team', title: requestTitle } : null } satisfies CreateThreadRequest); setBody(''); setRequestTitle(''); setRequest(false); }, request ? 'Information requested' : 'Message posted'); }
  return <div className="space-y-5">{Boolean(error) && <Banner tone="error">{error instanceof Error ? error.message : 'Could not save message.'}</Banner>}{canWrite && <Card><CardHeader title="Start a conversation" /><CardBody className="space-y-3"><p className="text-sm text-slate-600">About: {selectedAnchor[0]} {selectedAnchor[1] || 'as a whole'}</p>{rights.staff && <FormField label="Visibility"><Select value={visibility} onChange={e => setVisibility(e.target.value)} disabled={rights.expert}><option value="shared">Shared with research team</option><option value="internal">Internal — not visible to the research team</option></Select></FormField>}{visibility === 'internal' && <Banner tone="info">Internal — not visible to the research team</Banner>}<FormField label="Message" error={fieldError(error, 'body')}><Textarea value={body} onChange={e => setBody(e.target.value)} /></FormField>{rights.coordinator && visibility === 'shared' && <><Checkbox label="Request information from team" checked={request} onChange={e => setRequest(e.target.checked)} />{request && <FormField label="What the team needs to do" error={fieldError(error, 'action_item.title')}><Input value={requestTitle} onChange={e => setRequestTitle(e.target.value)} /></FormField>}</>}<Button loading={busy} disabled={!body.trim() || (request && !requestTitle.trim())} onClick={create}>{request ? 'Request information' : 'Post message'}</Button></CardBody></Card>}
    <QueryState loading={threads.isPending} error={threads.error} empty={threads.data?.items.length === 0}><div className="space-y-4">{threads.data?.items.map(thread => <Card key={thread.id} id={`thread-${thread.id}`}><CardHeader title={`${thread.anchor_type === 'project' ? 'Project' : thread.anchor_type}: ${thread.anchor_key || project.title}`} actions={<span className="text-xs font-semibold text-slate-600">{thread.visibility === 'internal' ? 'Internal — not visible to the research team' : 'Shared'}</span>} /><CardBody className={thread.visibility === 'internal' ? 'space-y-3 bg-amber-50' : 'space-y-3'}>{thread.action_items.map(item => <div key={item.id} className="flex flex-wrap items-center gap-2 rounded bg-white p-2"><strong className="text-sm">{item.title}</strong><StatusBadge status={item.status} />{rights.coordinator && item.status === 'open' && <Button size="sm" loading={busy} onClick={() => void run(() => apiPost(`/action-items/${item.id}/resolve`), 'Action item resolved')}>Resolve</Button>}</div>)}{thread.messages.map(message => <div key={message.id} className="border-b border-slate-200 pb-2 text-sm"><p className="font-semibold">{message.author_name} <span className="font-normal text-slate-500">· <DateText value={message.created_at} time /></span></p><p className="whitespace-pre-wrap">{message.body}</p></div>)}{canWrite && (thread.visibility === 'shared' ? !rights.expert : rights.staff) && <div className="flex gap-2"><Input aria-label="Reply" placeholder="Write a reply" value={replies[thread.id] ?? ''} onChange={e => setReplies(v => ({ ...v, [thread.id]: e.target.value }))} /><Button loading={busy} disabled={!replies[thread.id]?.trim()} onClick={() => void run(async () => { await apiPost(`/threads/${thread.id}/messages`, { body: replies[thread.id] } satisfies PostMessageRequest); setReplies(v => ({ ...v, [thread.id]: '' })); }, 'Reply posted')}>Reply</Button></div>}</CardBody></Card>)}</div></QueryState></div>;
}
